server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/svmdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Taipei
    username: root
    password: root+123

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
feign:
  okhttp:
    enabled: true

teamplus:
  flag: 1  # 0:-> Off, 1:-> On
  name: teamPlus
  url: https://eim.gtcloud.net.tw/API/SuperHubService.ashx?ask=
  ask: broadcastMessage
  ch_sn: 1
  key: 7e055a9dcd1f4456a06e9b4233b0d07d
  type: 1

xsms:
  flag: 0  # 0:-> Off, 1:->On
  name: SMS
  url: http://xsms.aptg.com.tw/XSMSAP/api/APIRTFastHttpRequest
  mdn: 0906180640
  uid: bb_test
  pwd: 123456
  call: 0906180640

mail:
  host: smtp.gmail.com
  port: 587
  auth_enabled: true
  starttls_enabled: true
  user_address: aptg.alert@gmail.com
  user_pwd: aptgalert123
  user_display_name: Notification Mail